In [ ]:
#Data analysis:-cleansing and modelling the data
#python provides various libraries which are used for data analysis,data manipulation as well as for data visualisation
#1)numpy:-this is mainley used for scientific computing


In [13]:

pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [16]:
import numpy as np


In [17]:
#creating a array
lst=[1,2,3,4,5,6,7,8,9]
arr=np.array(lst)

In [18]:
print(arr)

[1 2 3 4 5 6 7 8 9]


In [19]:
#creating a 2 dimensional array
lst1=[1,2,3,4,0],[5,6,7,8,9]
arr1=np.array(lst1)
print(arr1)

[[1 2 3 4 0]
 [5 6 7 8 9]]


In [22]:
#dimensions of a array
arr1.ndim

2

In [23]:
#shape of a array
arr1.shape

(2, 5)

In [26]:
#data type of array
print(arr1.dtype)

int32


In [31]:
#to print ones and zeros
zeroarr=np.zeros((6,4))
print(zeroarr)
onearr=np.ones((3,5))
print(onearr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [32]:
#creating an empty array
mty=np.empty((2,3))
mty

array([[0., 0., 0.],
       [0., 0., 0.]])

In [34]:
#to print a range of values
np.arange(2,9)

array([2, 3, 4, 5, 6, 7, 8])

In [35]:
#to print a identity matrix
np.eye(5,6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.]])

In [37]:
#pseudo random number generation
sample=np.random.randn(6)
sample

array([ 1.24234464,  0.24720008,  1.80128317,  0.11702851,  0.795857  ,
       -1.13422949])

In [43]:
#reshape a array
np.random.randn(10).reshape(2,5)

array([[-0.53119249,  2.95699194,  1.14146244,  0.93161537,  1.67776721],
       [ 0.04594452, -1.16433143,  1.64207887,  0.29317058,  0.2981657 ]])

In [54]:
#indexing a array

print(arr1[0])
print(arr1[0][1])

[1 2 3 4 0]
2


In [56]:
#slicing a array
print(arr[0:2])

[1 2]


In [68]:
#mathematical methods in numpy
print(np.mean(arr1))
print(np.median(arr1))
print(np.min(arr1))
print(np.max(arr1))
print(np.sum(arr1))

print(np.cumsum(arr1))
print(np.std(arr1))
print(np.cumprod(arr1))

print(np.sqrt(arr1))
print(np.exp(arr1))
print(np.abs(arr1))
print(np.square(arr1))
print(np.rint(arr1))
print(np.ceil(arr1))
print("@@@@@@@")

4.5
4.5
0
9
45
[ 1  3  6 10 10 15 21 28 36 45]
2.8722813232690143
[ 1  2  6 24  0  0  0  0  0  0]
[[1.         1.41421356 1.73205081 2.         0.        ]
 [2.23606798 2.44948974 2.64575131 2.82842712 3.        ]]
[[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
  1.00000000e+00]
 [1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
  8.10308393e+03]]
[[1 2 3 4 0]
 [5 6 7 8 9]]
[[ 1  4  9 16  0]
 [25 36 49 64 81]]
[[1. 2. 3. 4. 0.]
 [5. 6. 7. 8. 9.]]
[[1. 2. 3. 4. 0.]
 [5. 6. 7. 8. 9.]]
@@@@@@@


In [69]:
#sorting in numpy
np.sort(arr1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])